### ISSUE TITLE
why so many names

### ISSUE THREAD

**Issue by tj-commits** [jorgebucaran/colorette#105]
You first called it Clor, then Clorox, then Turbocolor, and now Colorette? Why did you change the name so much

**Comment by jorgebucaran** [comment]
Honestly, I never liked the original name. It wasn't something I connected with. I actually preferred the second name because it reminded me of the bleach product, which made it feel like a funny pun. If I remember correctly, at the time, I was still using the prototype chain based architecture, which was similar to the original Chalk, or maybe the current one still? I ended up rewriting the entire thing from scratch, essentially throwing out everything and coming up with something closer to the current, much simpler approach. I changed the name again before eventually settling on Colorette, which does not make it solely about performance. I also like this name the best.
