### ISSUE TITLE
Add kleur and kleur’s author mention to docs as inspiration

### ISSUE THREAD

**Issue by ai** [jorgebucaran/colorette#79]
It seems like the idea of color functions export was copied from `kleur`:

1. 9 Jul 2018 in `kleur`: https://github.com/lukeed/kleur/commit/41e46965738fca5b20e8b7e2e389e812b3200407
2. 11 Jul 2018 in `colorette`: https://github.com/jorgebucaran/colorette/commit/0226f478e6ba8ac3060187fdf29383314900f072

You should give honor to `kleur` author and mention him in docs.

**Comment by jorgebucaran** [comment]
I encourage everyone to go through the git history both ways. There was cross-pollination (from both sides). [I said it](https://twitter.com/jorgebucaran/status/1441840288792604678). 

These commits go back to when [the project was named Clorox](https://github.com/jorgebucaran/colorette/tree/0226f478e6ba8ac3060187fdf29383314900f072#clorox), and we still used the familiar chalk-like prototype-based API. Colorette, in its current incarnation, was realized _after_ I switched away from prototypes, at which point it had nothing to do with kleur or chalk, implementation-wise.

**Comment by ai** [comment]
Cross-pollination still mean that you need to mention `kleur`

**Comment by jorgebucaran** [comment]
You are missing the point. Colorette doesn't use prototypes anymore. It used to. Back then, it also [had a different name](https://github.com/jorgebucaran/colorette/tree/0226f478e6ba8ac3060187fdf29383314900f072#clorox) and it even had a different home in npm. kleur was also prototype-based at the time. 

I wouldn't expect kleur to mention Colorette either since its API is entirely different. Both our APIs and implementation have diverged beyond recognition. The only thing we have in common now is that we both colorize terminal text.

**Comment by ai** [comment]
I am talking about color functions export like `let { red } = require(x)`. Seems like in `kleur` this API was 3 days before the Colorette.

**Comment by jorgebucaran** [comment]
That's not how kleur API works at all. 

```js
kleur.blue().bold().underline("foo") // kleur
```
```js
blue(bold(underline("foo"))) // Colorette
```

I introduced the current API [here](https://github.com/jorgebucaran/colorette/tree/214efe5a698a937baa5e559250264cb0e12d3076). At that point, kleur and Colorette no longer resembled each other. Also, keep in mind that the previous incarnation of Colorette predates kleur several years.
